env:
  SEGMENT_CONTEXTS: 'snyk,npm,aws-credentials'
  SEGMENT_BUILDKITE_IMAGE: 'buildkite-agent-node12'

steps:
  - label: '🐳 Test & Build'
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - yarn install --frozen-lockfile
      - NODE_ENV=production yarn build
      - yarn lint
      - yarn test
      - mv node_modules node_modules_dev
      - yarn install --frozen-lockfile --production
      - node -e "require('./dist/src/boot'); process.exit(0)"
      - make -f .buildkite/Makefile.ci ci-docker-build
      - mv node_modules node_modules_prod
      - mv node_modules_dev node_modules
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v3.0.0:
          key: "v1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['node_modules/', 'dist/']
          save: true

  - label: '🔒 Snyk Security Check'
    agents:
      queue: v1
    plugins:
      - ssh://git@github.com/segmentio/snyk-buildkite-plugin#v1.4.1:
          runtime: npm
          severity-threshold: high
          fail-on: upgradable

  - wait: ~

  - label: '📡 Publish to Trebuchet'
    branches: master staging
    plugins:
      - ssh://git@github.com/segmentio/treb-publish-buildkite-plugin#v0.5.0:
          configs:
            - .run/fab-5-engine.yml
