steps:
  - label: 'Test'
    env:
      SEGMENT_CONTEXTS: 'snyk,npm,aws-credentials'
      SEGMENT_BUILDKITE_IMAGE: 'buildkite-agent-node12'
    agents:
      queue: v1
    commands: |
      echo '--- Configuring NPM auth'
      npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}

      echo '--- Fetching dependencies'
      npm install
      PATH=$(npm bin):$PATH

      echo '--- Snyk scan'
      bk-snyk

      echo '--- Linting'
      npm run lint

      echo '--- Testing'
      npm run test
